### ISSUE TITLE
tifast send -m fails, tifast send works ok 

### ISSUE THREAD

**Issue by dimovdaniel** [ulizama/TiFastlane#18]
```
 tifast send -m
Sending only Metadata
/Users/dimovdaniel/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/command.rb:164:in `parse_options_and_call_procs': invalid option: --skip-deploy (OptionParser::InvalidOption)
    from /Users/dimovdaniel/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Users/dimovdaniel/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Users/dimovdaniel/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /Users/dimovdaniel/.rvm/gems/ruby-2.1.2@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Users/dimovdaniel/.rvm/gems/ruby-2.1.2@global/gems/deliver-1.3.3/lib/deliver/commands_generator.rb:84:in `run'
    from /Users/dimovdaniel/.rvm/gems/ruby-2.1.2@global/gems/deliver-1.3.3/lib/deliver/commands_generator.rb:12:in `start'
    from /Users/dimovdaniel/.rvm/gems/ruby-2.1.2@global/gems/deliver-1.3.3/bin/deliver:5:in `<top (required)>'
    from /Users/dimovdaniel/.rvm/rubies/ruby-2.1.2/bin/deliver:23:in `load'
    from /Users/dimovdaniel/.rvm/rubies/ruby-2.1.2/bin/deliver:23:in `<main>'
    from /Users/dimovdaniel/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
    from /Users/dimovdaniel/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

Done
```

**Comment by dimovdaniel** [comment]
```
function uploadMetadata(){
    if (!fs.existsSync(appDeliveryDir + "/Deliverfile")){
        console.log(chalk.red('You need to run "tifast init" first'));
        return;
    }

    var initArgs = [
        '--skip-deploy'
    ];

    exec('deliver', initArgs, { cwd: appDeliveryDir }, function(e){
        console.log(chalk.green('\nDone\n'));
    });
};
```

I can't find --skip-deploy as valid option for deliver

**Comment by DouglasHennrich** [comment]
Deliver has update, i need update tifast too to work with the new version od Deliver

**Comment by DouglasHennrich** [comment]
I speak with the owner of Deliver and he says he take off this command... I will update `tifast` to work around this problem and be apple to update metadata and screenshots without uploading the binary again. Thanks for the reply

**Comment by DouglasHennrich** [comment]
Problem fixed
[0.3.7](https://github.com/ulizama/TiFastlane/commit/29cbddb88262588a7b68503a9e6e241de8348c48)
