### ISSUE TITLE
Error on tifast init -s

### ISSUE THREAD

**Issue by caspahouzer** [ulizama/TiFastlane#20]
I did as it is written in the readme. first tifast setup, filled out all questions. Second, ran tifast init -s, because my app is already in the store.

ends with

```
tifast init -s
Initializing TiFastLane Smart Mode
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn deliver ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

What can I do? What do you need to help me?

**Comment by ulizama** [comment]
Hi @caspahouzer, are you till having the issue?
