### ISSUE TITLE
Starting Deliver error

### ISSUE THREAD

**Issue by jmcerrejon** [ulizama/TiFastlane#22]
When I use tifast send or tifast init, I get:

```
Starting Deliver

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by ulizama** [comment]
Can you confirm your version?

`tifast version`

**Comment by jmcerrejon** [comment]
0.4.0

**Comment by ulizama** [comment]
This is indeed really strange. I haven't been able to reproduce the bug. Can you please show me your `tifastlane.cfg`?

**Comment by jmcerrejon** [comment]
```
{
   "cli": "appc" 
 , "locale": "en-US" 
 , "apple_id": "nc@soporttec.es" 
 , "team_id": "null" 
 , "team_name": "null" 
 , "google_play_key": "GooglePlayKey.p12" 
 , "google_play_issuer": "gruponcsaluddeveloper@gmail.com" 
}
```

**Comment by ulizama** [comment]
Ok, looks good.

What is the name of your app in your `tiapp.xml` file?

**Comment by jmcerrejon** [comment]
I removed appc-app-id and guid here:

```
<?xml version="1.0" encoding="UTF-8"?>
<ti:app xmlns:ti="http://ti.appcelerator.org">
    <id>com.soporttec.farmaapp</id>
    <name>FarmaApp</name>
    <version>1.0.0.3</version>
    <publisher>Jose Manuel Cerrejon Gonzalez</publisher>
    <url>http://soporttec.com</url>
    <description>Esta aplicación te pone en contacto directo con tu farmacia y podrás enterarte de las promociones, servicios y productos de la forma más fácil.</description>
    <copyright>2015 by Soporttec</copyright>
    <icon>appicon.png</icon>
    <fullscreen>false</fullscreen>
    <navbar-hidden>false</navbar-hidden>
    <analytics>true</analytics>
    <guid>my_gu_id</guid>
    <property name="ti.ui.defaultunit" type="string">dp</property>
    <ios>
        <plist>
            <dict>
                <key>UIBackgroundModes</key>
                <array>
                    <string>fetch</string>
                    <string>remote-notification</string>
                </array>
                <key>UISupportedInterfaceOrientations~iphone</key>
                <array>
                    <string>UIInterfaceOrientationPortrait</string>
                </array>
                <key>UISupportedInterfaceOrientations~ipad</key>
                <array>
                    <string>UIInterfaceOrientationPortrait</string>
                    <string>UIInterfaceOrientationPortraitUpsideDown</string>
                    <string>UIInterfaceOrientationLandscapeLeft</string>
                    <string>UIInterfaceOrientationLandscapeRight</string>
                </array>
                <key>UIRequiresPersistentWiFi</key>
                <false/>
                <key>UIPrerenderedIcon</key>
                <false/>
                <key>UIStatusBarHidden</key>
                <false/>
                <key>UIStatusBarStyle</key>
                <string>UIStatusBarStyleDefault</string>
            </dict>
        </plist>
    </ios>
    <android xmlns:android="http://schemas.android.com/apk/res/android">
        <manifest android:versionCode="1" android:versionName="1.0.0.3">
            <uses-permission android:name="android.permission.READ_CALENDAR"/>
            <uses-permission android:name="android.permission.WRITE_CALENDAR"/>
            <uses-sdk android:minSdkVersion="17" android:targetSdkVersion="21"/>
            <application android:theme="@style/Theme.Pharmacy_theme">
                <activity android:configChanges="keyboardHidden" android:screenOrientation="portrait">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN"/>
                        <category android:name="android.intent.category.LAUNCHER"/>
                    </intent-filter>
                </activity>
            </application>
        </manifest>
    </android>
    <modules>
        <module platform="iphone" version="1.8.2">dk.napp.social</module>
        <module platform="commonjs" version="1.1.8">reste</module>
        <module platform="android" version="0.6">com.rkam.swiperefreshlayout</module>
        <module platform="commonjs" version="1.3.4">nl.fokkezb.html2as</module>
    </modules>
    <deployment-targets>
        <target device="android">true</target>
        <target device="ipad">false</target>
        <target device="iphone">true</target>
        <target device="mobileweb">false</target>
        <target device="windows">false</target>
    </deployment-targets>
    <sdk-version>5.0.3.v20151022152331</sdk-version>
    <plugins>
        <plugin version="1.0">ti.alloy</plugin>
    </plugins>
    <property name="appc-app-id" type="string">my appc-app-id</property>
</ti:app>

```

**Comment by DouglasHennrich** [comment]
Can you please paste your `Deliver` file here?

And please confirm you have all `fastlane tools` which `tifast` use.
- Deliver: `deliver -v`
- PEM: `pem -v`
- Sigh: `sigh -v`
- Produce: `produce -v`
- Pilot: `pilot -v`
- Supply: `supply -v`

by the way... you're running on app's root folder right?

Thanks

**Comment by jmcerrejon** [comment]
When I run all those commands, I get `command not found` in the app's root folder :/

I'll follow the installation guide this weekend again and post here the result.

**Comment by DouglasHennrich** [comment]
If you're running that codes and getting `command not found`, theses commands have failed to download when you download `tifastlane` by `npm install -g tifastlane`

What's your `gem -v` ?

**Comment by jmcerrejon** [comment]
I've installed tifastlane and now I get another issue:

```
Starting Deliver
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.1/lib/fastlane_core/configuration/configuration_file.rb:28:in `rescue in initialize': Syntax error in your configuration file './Deliverfile' on line 47: (eval):47: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '(' (RuntimeError)
...he last step for the deployment process, where you define if...
...                               ^
(eval):47: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
...e deployment process, where you define if you use third part...
...                               ^
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.1/lib/fastlane_core/configuration/configuration_file.rb:22:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.1/lib/fastlane_core/configuration/configuration.rb:115:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.1/lib/fastlane_core/configuration/configuration.rb:115:in `load_configuration_file'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.6.6/lib/deliver/commands_generator.rb:38:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.6.6/lib/deliver/commands_generator.rb:107:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.6.6/lib/deliver/commands_generator.rb:12:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.6.6/bin/deliver:5:in `<top (required)>'
    from /usr/bin/deliver:23:in `load'
    from /usr/bin/deliver:23:in `<main>'

Deliver Done
```

More info:

```
gem -v
2.0.14
deliver -v
deliver 1.6.6
pem -v
pem 1.1.1
sigh -v
sigh 1.2.1
produce -v
produce 1.1.1
pilot -v
pilot 1.2.1
supply -v
supply 0.2.2
```

**Comment by ulizama** [comment]
There is a syntax error in your Deliverfile Please post the contents of
your file and we can help you debug it.

Thanks

**Comment by jmcerrejon** [comment]
I changed some values here for security ;)

```
###################### App Metadata ######################
# Update the app description and metadata in the ./metadata folder

###################### Screenshots ######################
# Store all screenshots in the ./screenshots folder separated
# by language.

###################### App Information ######################
app_identifier "com.johndoe.test"
username "nc@gmail.com" # the login email address

# Pass the price tier as number. This will be active from the current day. 0 = free
price_tier 0

# A path to a new app icon, which must be exactly 1024x1024px
app_icon "../../DefaultIcon.png"

# The up to date copyright information.
copyright "#{Time.now.year} TiDeveloper"

# The english name of the category you want to set (e.g. Business, Books)
primary_category "Medical"

# The english name of the secondary category you want to set
secondary_category "Catalogs"

# Should the app be released to all users once Apple approves it? If set to false, you'll have to manually release the update once it got approved.
automatic_release false

# Contact information for the app review team. Available options: first_name, last_name, phone_number, email_address, demo_user, demo_password, notes.
app_review_information(
  first_name: "John",
  last_name: "Doe",
  phone_number: "34555584652",
  email_address: "john@gmail.com",
  demo_user: "john@gmail.com",
  demo_password: "myhappypassword",
  notes: "My custom notes"
)

# You can set the app age ratings using deliver. You'll have to create and store a JSON configuration file.
# The keys/values on the top allow values from 0-2, and the items on the bottom allow only 0 or 1.
app_rating_config_path "./ratings.json"

# Please, read this information https://github.com/KrauseFx/deliver/blob/master/Reference.md

Must be a hash. This is used as the last step for the deployment process, where you define if you use third party content or use encryption.
submission_information({
   add_id_info_serves_ads: false,
   add_id_info_limits_tracking: false,
   add_id_info_tracks_action: true,
   add_id_info_tracks_install: true,
   add_id_info_uses_idfa: true,
   content_rights_contains_third_party_content: false,
   content_rights_has_rights: false,
   export_compliance_available_on_french_store: false,
   export_compliance_ccat_file: false,
   export_compliance_contains_proprietary_cryptography: false,
   export_compliance_is_exempt: false,
   export_compliance_uses_encryption: false,
   export_compliance_encryption_updated: false,
   export_compliance_compliance_required: false
})

###################### More Options ######################
# If you want to have even more control, check out the documentation
# https://github.com/KrauseFx/deliver/blob/master/Deliverfile.md

```

**Comment by ulizama** [comment]
Ok, we had a bug in the CLI generator of the `Deliverfile`.

Please change the following line:

`Must be a hash. This is used as the last step for the deployment process, where you define if you use third party content or use encryption.`

to

`# Must be a hash. This is used as the last step for the deployment process, where you define if you use third party content or use encryption.`

As you see the line should be a comment.

**Comment by jmcerrejon** [comment]
```
Starting Deliver
[18:59:43]: Error setting value './ratings.json' for option 'app_rating_config_path'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.1/lib/fastlane_core/configuration/configuration_file.rb:24:in `eval': Could not find config file at path './ratings.json' (RuntimeError)
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.1/lib/fastlane_core/configuration/config_item.rb:61:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.1/lib/fastlane_core/configuration/config_item.rb:61:in `valid?'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.1/lib/fastlane_core/configuration/config_item.rb:45:in `verify!'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.1/lib/fastlane_core/configuration/configuration.rb:179:in `set'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.1/lib/fastlane_core/configuration/configuration_file.rb:37:in `method_missing'
    from (eval):43:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.1/lib/fastlane_core/configuration/configuration_file.rb:24:in `eval'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.1/lib/fastlane_core/configuration/configuration_file.rb:24:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.1/lib/fastlane_core/configuration/configuration.rb:115:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.1/lib/fastlane_core/configuration/configuration.rb:115:in `load_configuration_file'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.6.6/lib/deliver/commands_generator.rb:38:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.6.6/lib/deliver/commands_generator.rb:107:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.6.6/lib/deliver/commands_generator.rb:12:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.6.6/bin/deliver:5:in `<top (required)>'
    from /usr/bin/deliver:23:in `load'
    from /usr/bin/deliver:23:in `<main>'

Deliver Done
```

My rating.json:

```
{
   "CARTOON_FANTASY_VIOLENCE": 0,
   "REALISTIC_VIOLENCE": 0,
   "PROLONGED_GRAPHIC_SADISTIC_REALISTIC_VIOLENCE": 0,
   "PROFANITY_CRUDE_HUMOR": 0,
   "MATURE_SUGGESTIVE": 0,
   "HORROR": 0,
   "MEDICAL_TREATMENT_INFO": 0,
   "ALCOHOL_TOBACCO_DRUGS": 0,
   "GAMBLING": 0,
   "SEXUAL_CONTENT_NUDITY": 0,
   "GRAPHIC_SEXUAL_CONTENT_NUDITY": 0,


   "UNRESTRICTED_WEB_ACCESS": 0,
   "GAMBLING_CONTESTS": 0
}
```

**Comment by DouglasHennrich** [comment]
Do you have that file on same folder that `Deliver` file ?

**Comment by jmcerrejon** [comment]
Yes

![img](http://i65.tinypic.com/4ibuhh.png)

**Comment by DouglasHennrich** [comment]
`ratingS.json` != `rating.json`

**Comment by DouglasHennrich** [comment]
Thanks for your feedback @jmcerrejon
