### ISSUE TITLE
tifast register - throws unhandled error

### ISSUE THREAD

**Issue by yozef** [ulizama/TiFastlane#24]
```
$>tifast setup
? Which CLI do you want to use? Appcelerator
? What locale do you want to use? en-US
? What's your apple@id.com? dfdf@sfg.com
? What's your TEAM ID? Leave it if you don't want to use it
? What's your TEAM NAME? Leave it if you don't want to use it
? What's your Google Play Key File? (leave empty for default) GooglePlayKey.p12
? What's the Google Play Issuer Email? Leave if you don't want to use it sfgsfg@sfgfsg.com

tifastlane.cfg created
All Done!
```

then...

```
$> tifast init
Initializing TiFastLane
Your app "deliver" configuration has been created.
You can find your configuration files on: ./TiFLDelivery/com.xxx.yyyy
Go in and tweak your configuration.

$> tifast status

Apple ID: adfj@gmail.com
Name: XYUZ
AppId: com.xxx.yyyy
Version: 1.0
CFBundleVersion: 0
GUID: h12345-x67894-345-356-f987348
```

```
$> tifast register
Creating app on Apple Developer Portal & iTunes Connect
APP ID: com.xxx.yyyy
APP Name: zzzzzz
Version: 1.0
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn produce ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by ulizama** [comment]
Can you please confirm your version of TiFast:
`tifast -v`

And let's make sure you have the latest version of deliver:
`deliver -v`

**Comment by yozef** [comment]
Thanks @ulizama for getting back to me.

```
tifast -v
0.4.5
```

```
$> deliver -v
-bash: deliver: command not found
$> tifast deliver -v
0.4.5
```

Question - Should I have the App Id registered on Apple Dev portal? If so, the setup never asked me for the Apple password account - Could it be that?

**Comment by ulizama** [comment]
That's the problem. Our install process has some issues sometimes installing the `fastlane` tools we need. Please run the following command:

`sudo gem install deliver sigh produce pem pilot supply`

**Comment by yozef** [comment]
Excellent. Thanks!
