### ISSUE TITLE
Fails to deliver with crash

### ISSUE THREAD

**Issue by ManadayM** [ulizama/TiFastlane#3]
I am trying to submit my app through this tool since morning. I successfully registered my app on Developer Apple and iTunes connect. The only issue I'm facing is with `tifastlane sendapp` command to submit my app. Could anyone please help here?
#### Exception

```
Starting deliver
execvp(): No such file or directory

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```
#### Deliverfile

```
###################### App Information ######################
app_identifier "<my-app-id>"
apple_id "[ID]" # This is NOT your Apple login ID, but the App ID of your app
email "<email-address>" # the login email address


###################### More Options ######################
# If you want to have even more control, check out the documentation
# https://github.com/KrauseFx/deliver/blob/master/Deliverfile.md

copyright "#{Time.now.year} Company"

automatic_release false

app_review_information(
  first_name: "Manaday",
  last_name: "Mavani",
  phone_number: "123123",
  email_address: "mavani.manaday@abc.com",
  demo_user: "demoUser",
  demo_password: "demoPass",
  notes: "such notes, very text"
)

primary_category "Finance"
secondary_category "Business"

price_tier 0

submit_further_information({
  export_compliance: {
    encryption_updated: false,
    cryptography_enabled: false,
    is_exempt: false
  },
  third_party_content: {
    contains_third_party_content: false,
    has_rights: false
  },
  advertising_identifier: {
    use_idfa: false,
    serve_advertisement: false,
    attribute_advertisement: false,
    attribute_actions: false,
    limit_ad_tracking: false
  }
})
```
#### Platform Details

**Operating System**
- Name                        = Mac OS X
- Version                     = 10.10
- Architecture                = 64bit

**Node.js**
- Node.js Version             = 0.10.13
- npm Version                 = 1.3.2

**Titanium CLI**
*CLI Version                 = 3.4.2

**Titanium SDK**
- SDK Version                 = 3.5.1.GA

**Comment by ManadayM** [comment]
After spending hours I found that the deliver module was not installed on my machine. I tried to install the same and found that it was requiring me to install latest version of XCode Command Line Tools. Installing command line tools and then the deliver module fixed the issue!
