### ISSUE TITLE
When trying to run "tifast setup" I get the following error

### ISSUE THREAD

**Issue by mmeyer12** [ulizama/TiFastlane#57]
`usr/local/lib/node_modules/tifastlane/node_modules/inquirer/lib/prompts/list.js:32
      let index = _.findIndex(this.opt.choices.realChoices, ({ value }) => value === def);
                                                             ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Function.promptModule.restoreDefaultPrompts (/usr/local/lib/node_modules/tifastlane/node_modules/inquirer/lib/inquirer.js:55:33)
    at Object.inquirer.createPromptModule (/usr/local/lib/node_modules/tifastlane/node_modules/inquirer/lib/inquirer.js:65:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/tifastlane/node_modules/inquirer/lib/inquirer.js:77:28)`

**Comment by gimdongwoo** [comment]
Please, check your Node version.

`inquirer 4.x` is need to Node 6 and above.

**Comment by mmeyer12** [comment]
Can I change the inquirer to use an older node? Titanium SDK will not allow running of node 6.0.

Titanium Release Notes:
Node 4.2.0 is now a minimum requirement and Node 4.6.x is maximum version supported

**Comment by gimdongwoo** [comment]
Actually Titanium SDK 5+ is supported Node 6+.
I use Node 8.9 and Ti SDK 6.3.
It works perfectly.

**Comment by mmeyer12** [comment]
Right now I am on Ti SDK 5.5.1.GA and when I go to Node 6 we break.

**Comment by gimdongwoo** [comment]
I have released a fixed version of this issue.
Please update tifastlane. Thank you!

**Comment by mmeyer12** [comment]
Works now, thank you for the fast service
