### ISSUE TITLE
Error on tifast init -s

### ISSUE THREAD

**Issue by mmeyer12** [ulizama/TiFastlane#59]
When I go to the next step I get the following error running tifast int -s

➜  mobile git:(master) ✗ tifast init -s
/usr/local/lib/node_modules/tifastlane/node_modules/tiapp.xml/lib/tiapp.xml.js:40
		throw new Error('No XML document created', str);
		^

Error: No XML document created
    at Object.parse (/usr/local/lib/node_modules/tifastlane/node_modules/tiapp.xml/lib/tiapp.xml.js:40:9)
    at Object.load (/usr/local/lib/node_modules/tifastlane/node_modules/tiapp.xml/lib/tiapp.xml.js:61:17)
    at Object.exports.loadconfig (/usr/local/lib/node_modules/tifastlane/index.js:70:22)
    at Command.init (/usr/local/lib/node_modules/tifastlane/cli.js:203:16)
    at Command.listener (/usr/local/lib/node_modules/tifastlane/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/usr/local/lib/node_modules/tifastlane/node_modules/commander/index.js:653:12)
    at Command.parse (/usr/local/lib/node_modules/tifastlane/node_modules/commander/index.js:475:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/tifastlane/cli.js:174:9)

**Comment by mmeyer12** [comment]
Sorry about this. I was told to be in the root of the file, but I needed to drill down one dir where my ti.app was located
