### ISSUE TITLE
packageName and packageVersion required

### ISSUE THREAD

**Issue by brownemint** [ulizama/TiFastlane#7]
Hi,

I'm getting the following error when running tifastlane from inside my Titanium project directory

```
(44) ~/Documents/Titanium/rxm-appv3 -> tifast -h

/usr/local/lib/node_modules/tifastlane/node_modules/update-notifier/index.js:15
        throw new Error('packageName and packageVersion required');
              ^
Error: packageName and packageVersion required
    at new UpdateNotifier (/usr/local/lib/node_modules/tifastlane/node_modules/update-notifier/index.js:15:9)
    at module.exports (/usr/local/lib/node_modules/tifastlane/node_modules/update-notifier/index.js:118:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/tifastlane/cli.js:11:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

During installation, when prompted with `#node-sudo-passwd#` it failed to accept my password all 3 times, but still says I downloaded the following:

```
--- All Tools Downloaded ---
tifastlane@0.3.0 /usr/local/lib/node_modules/tifastlane
├── underscore@1.8.3
├── xpath@0.0.9
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── tiapp.xml@0.2.2 (pretty-data2@0.40.1, xmldom@0.1.19)
├── sudo@1.0.3 (inpath@1.0.2, pidof@1.0.2, read@1.0.7)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
└── update-notifier@0.2.2 (is-npm@1.0.0, semver-diff@2.0.0, string-length@1.0.1, configstore@0.3.2, latest-version@1.0.1)
```

Before trying to install tifastlane through npm, I did successfully install fastlane using the following `sudo gem install fastlane --verbose`

I am using version 1.4.28 of npm and version 0.10.32 of node

Any idea on how to get tifastlane working? I'd love to try it out. Looks like a great tool!

**Comment by beezenees** [comment]
Getting the same error -

```
/Users/jcomdev/.node/lib/node_modules/tifastlane/node_modules/update-notifier/index.js:15
        throw new Error('packageName and packageVersion required');
              ^
Error: packageName and packageVersion required
    at new UpdateNotifier (/Users/jcomdev/.node/lib/node_modules/tifastlane/node_modules/update-notifier/index.js:15:9)
    at module.exports (/Users/jcomdev/.node/lib/node_modules/tifastlane/node_modules/update-notifier/index.js:118:23)
    at Object.<anonymous> (/Users/jcomdev/.node/lib/node_modules/tifastlane/cli.js:11:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

**Comment by ulizama** [comment]
I just updated to 0.3.2, please confirm if the issue persists on that version.

**Comment by brownemint** [comment]
Working fine for me now.
Thanks!!
